const dataSDM = [
    {
        'name': 'Jumlah pendidikan dan pelatihan pegawai',
        'target': 464,
        'real': 3386,
        'bobot': 11.11,
        'capaian_individu': 729.74,
        'capaian': 81.08,
        'tahun': 2022,
    },
    {
        'name': 'Presentase Penambahan pegawai',
        'target': 6,
        'real': 17.51,
        'bobot': 11.11,
        'capaian_individu': 291.83,
        'capaian': 32.43,
        'tahun': 2022,
    },
    {
        'name': 'Jumlah sarana dan prasarana',
        'target': 63,
        'real': 55,
        'bobot': 11.11,
        'capaian_individu': 87.30,
        'capaian': 9.70,
        'tahun': 2022,
    },

    {
        'name': 'Jumlah pendidikan dan pelatihan pegawai',
        'target': 450,
        'real': 315,
        'bobot': 11.11,
        'capaian_individu': 70.74,
        'capaian': 7.78,
        'tahun': 2021,
    },
    {
        'name': 'Presentase Penambahan pegawai',
        'target': 6,
        'real': 5.97,
        'bobot': 11.11,
        'capaian_individu': 99.50,
        'capaian': 11.06,
        'tahun': 2021,
    },
    {
        'name': 'Jumlah sarana dan prasarana',
        'target': 60,
        'real': 48,
        'bobot': 11.11,
        'capaian_individu': 80,
        'capaian': 8.89,
        'tahun': 2021,
    },

    {
        'name': 'Jumlah pendidikan dan pelatihan pegawai',
        'target': 630,
        'real': 315,
        'bobot': 11.11,
        'capaian_individu': 203,
        'capaian': 50,
        'tahun': 2020,
    },
    {
        'name': 'Presentase Penambahan pegawai',
        'target': 5,
        'real': 10.77,
        'bobot': 11.11,
        'capaian_individu': 120,
        'capaian': 215.4,
        'tahun': 2020,
    },
    {
        'name': 'Jumlah sarana dan prasarana',
        'target': 63,
        'real': 89,
        'bobot': 11.11,
        'capaian_individu': 161.67,
        'capaian': 141,
        'tahun': 2020,
    },
]

export default dataSDM